# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [
  'exec-and-forget /opt/homebrew/bin/borders',
  'exec-and-forget /opt/homebrew/bin/sketchybar',
]

# Notify Sketchybar about workspace change
exec-on-workspace-change = [
    '/bin/bash',
    '-c',
    '/opt/homebrew/bin/sketchybar --trigger aerospace_workspace_change AEROSPACE_FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE AEROSPACE_PREV_WORKSPACE=$AEROSPACE_PREV_WORKSPACE',
]

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 45

# Possible values: tiles|accordion
default-root-container-layout = 'accordion'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
# on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = true

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 3
inner.vertical =   3
outer.left =       3
outer.bottom =     3
outer.top =        [{ monitor.'built-in' = 3}, 40]  # For sketchybar, on a notched macbook
outer.right =      3

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]
ctrl-space = ['mode alt']

# 'alt' binding mode declaration
[mode.alt.binding]
ctrl-space = ['mode alt']
space = ['mode main']
esc = ['mode alt']
backtick = ['reload-config', 'mode main', 'exec-and-forget /opt/homebrew/bin/sketchybar --reload']

slash = 'layout tiles horizontal vertical'
comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
h = 'focus --boundaries-action stop left'
j = 'focus --boundaries-action stop down'
k = 'focus --boundaries-action stop up'
l = 'focus --boundaries-action stop right'

c = ['move-mouse window-force-center']

# See: https://nikitabobko.github.io/AeroSpace/commands#move
shift-h = 'move left'
shift-j = 'move down'
shift-k = 'move up'
shift-l = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
minus = 'resize smart -64'
equal = 'resize smart +64'
shift-minus = 'resize smart -128'
shift-equal = 'resize smart +128'

u = 'workspace prev'
i = 'workspace next'
shift-u = 'move-node-to-workspace prev --focus-follows-window'
shift-i = 'move-node-to-workspace next --focus-follows-window'
1 = 'workspace 1'
2 = 'workspace 2'
3 = 'workspace 3'
4 = 'workspace 4'
5 = 'workspace 5'
6 = 'workspace 6'
7 = 'workspace 7'
8 = 'workspace 8'
9 = 'workspace 9'
p = 'focus-monitor prev --wrap-around'
n = 'focus-monitor next --wrap-around'
shift-p = 'move-workspace-to-monitor --wrap-around prev'
shift-n = 'move-workspace-to-monitor --wrap-around next'


# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
shift-1 = ['move-node-to-workspace 1 --focus-follows-window', 'workspace 1']
shift-2 = ['move-node-to-workspace 2 --focus-follows-window', 'workspace 2']
shift-3 = ['move-node-to-workspace 3 --focus-follows-window', 'workspace 3']
shift-4 = ['move-node-to-workspace 4 --focus-follows-window', 'workspace 4']
shift-5 = ['move-node-to-workspace 5 --focus-follows-window', 'workspace 5']
shift-6 = ['move-node-to-workspace 6 --focus-follows-window', 'workspace 6']
shift-7 = ['move-node-to-workspace 7 --focus-follows-window', 'workspace 7']
shift-8 = ['move-node-to-workspace 8 --focus-follows-window', 'workspace 8']
shift-9 = ['move-node-to-workspace 9 --focus-follows-window', 'workspace 9']

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
shift-tab = 'move-workspace-to-monitor --wrap-around next'

shift-r = ['flatten-workspace-tree', 'mode alt'] # reset layout
#s = ['layout sticky tiling', 'mode alt'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
f = ['fullscreen'] # Toggle between fullscreen
shift-f = ['layout floating tiling', 'mode alt'] # Toggle between floating and tiling layout

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
r =  'mode resize'
semicolon = 'mode spacial'
w = 'mode workspace'

[mode.resize.binding]
ctrl-space = ['mode alt']
space = 'mode main'
esc = 'mode alt'
r = 'mode alt'
h = ['resize width -64']
j = ['resize height -64']
k = ['resize height +64']
l = ['resize width +64']
shift-h = ['resize width -8']
shift-j = ['resize height -8']
shift-k = ['resize height +8']
shift-l = ['resize width +8']

[mode.spacial.binding]
ctrl-space = ['mode spacial']
space = 'mode main'
esc = 'mode alt'
h = ['join-with left', 'mode alt']
j = ['join-with down', 'mode alt']
k = ['join-with up', 'mode alt']
l = ['join-with right', 'mode alt']

[mode.workspace.binding]
ctrl-space = ['mode workspace']
space = 'mode main'
esc = 'mode alt'
w = 'mode alt'
h = ['workspace prev']
l = ['workspace next']
j = ['focus-monitor next']
k = ['focus-monitor prev']
shift-h = ['move-node-to-workspace prev --focus-follows-window']
shift-l = ['move-node-to-workspace next --focus-follows-window']
shift-k = ['move-node-to-monitor prev --focus-follows-window']
shift-j = ['move-node-to-monitor next --focus-follows-window']


# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# You can uncomment the following lines to open up terminal with alt + enter shortcut (like in i3)
# alt-enter = '''exec-and-forget osascript -e '
# tell application "Terminal"
#     do script
#     activate
# end tell'
# '''

# alt-shift-z = 'move-node-to-workspace Z --focus-follows-window'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

[workspace-to-monitor-force-assignment]
1 = 'main'
2 = 'main'
3 = 'main'
4 = 'main'
5 = 'main'
6 = ['secondary', 'main']
7 = ['secondary', 'main']
8 = ['secondary', 'main']
9 = ['secondary', 'main']

[[on-window-detected]]
if.app-id = 'com.1password.1password'
run = ['move-node-to-workspace 9',
]

